### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Turbogame** [TechieGuy12/PlexServerAutoUpdater#58]
Good morning,

I've updated to the latest release and set the location for my x64 Plex Installation folder. Now when I run the updater, I get the following error:

`
2022-10-30 09:44:38 Getting windows user.
2022-10-30 09:44:38 Checking if user is an administrator.
2022-10-30 09:44:38 Initializing the silent update.
2022-10-30 09:44:38 Getting the service user.
2022-10-30 09:44:38 The Plex service is installed. Let's get the user associated with the service.
2022-10-30 09:44:38 The Plex service user: XXX\XXX.
2022-10-30 09:44:38 Plex install folder: C:\Program Files\Plex\Plex Media Server\ .
2022-10-30 09:44:38 Plex local data folder: E:\.
2022-10-30 09:44:38 Updates folder: E:\Plex Media Server\Updates.
2022-10-30 09:44:38 Update channel: Plex Pass.
2022-10-30 09:44:38 Plex found in: C:\Program Files\Plex\Plex Media Server\Plex Media Server.exe.
2022-10-30 09:44:38 64-bit: True.
2022-10-30 09:44:38 Verify the updates folder is specified.
2022-10-30 09:44:38 Verify the updates folder, E:\Plex Media Server\Updates exists.
2022-10-30 09:44:38 Getting ready to download the latest package.
2022-10-30 09:44:38 Checking for the latest version from Plex.
2022-10-30 09:44:38 The update channel is set for Plex Pass.
2022-10-30 09:44:38 Sending request to Plex: https://plex.tv/api/downloads/5.json?channel=plexpass
2022-10-30 09:44:39 Parsing the information from Plex.
2022-10-30 09:44:39 The file, E:\Plex Media Server\Updates\1.29.2.6334-817e19b35\packages\PlexMediaServer-1.29.2.6334-817e19b35-x86_64.exe, exists. Checking to see if the package is valid.
2022-10-30 09:44:41 Checking if the installation package is valid.
2022-10-30 09:44:41 The package is valid. The checksums match.
2022-10-30 09:44:41 Since the package is valid - not downloading again.
2022-10-30 09:44:41 Latest packages file: E:\Plex Media Server\Updates\1.29.2.6334-817e19b35\packages\PlexMediaServer-1.29.2.6334-817e19b35-x86_64.exe
2022-10-30 09:44:41 The latest file version available for download is 1.29.2.6334.
2022-10-30 09:44:41 Current version: .
2022-10-30 09:44:41 Latest version: 1.29.2.6334.
2022-10-30 09:44:43 Checking for server update.
2022-10-30 09:44:43 Object reference not set to an instance of an object.
2022-10-30 09:44:43    at TE.Plex.MediaServer.IsUpdateAvailable()
   at TE.Plex.SilentUpdate.Run()
`

Config file settings:

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<startup>
		<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8"/>
	</startup>
  <appSettings>
    <add key="PlexServiceName" value="PlexService"/>
    <add key="PlexExecutable" value="Plex Media Server.exe"/>
    <add key="PlexUpdatesFolder" value="Plex Media Server\Updates"/>
    <add key="PlexPackagesFolder" value="packages"/>
    <add key="PlexInstallParameters" value="/install /quiet /norestart /log "/>
    <add key="PlexInstallParametersx64" value="/verysilent /norestart /log "/>
    <add key="PlexInstallLocation" value="C:\Program Files\Plex\Plex Media Server\ "/>
    <add key="PlexInstallLogFolder" value="PlexUpdater"/>
    <add key="PlexInstallLogFile" value="PlexMediaServerInstall.log"/>
  </appSettings>
</configuration>`

Am I doing something wrong? The PlexService service was running at the time as well.

**Comment by TechieGuy12** [comment]
It appears the updater can't get the version number for the installed Plex server. 

I can't reproduce the issue on my end, so I have created release [0.2.1.2-beta.1](https://github.com/TechieGuy12/PlexServerAutoUpdater/releases/tag/0.2.1.2-beta.1) with more logging to help determine if the version number can be retrieved from the currently installed Plex.

**Comment by Turbogame** [comment]
Ok, I've ran the new beta executable, and the logging is as follows:

2022-10-31 21:10:14 Getting windows user.
2022-10-31 21:10:14 Checking if user is an administrator.
2022-10-31 21:10:14 Initializing the update window.
2022-10-31 21:10:14 Initializing the timer object.
2022-10-31 21:10:14 Initializing the Plex media server object.
2022-10-31 21:10:14 Plex install folder: C:\Program Files\Plex\Plex Media Server.
2022-10-31 21:10:14 Getting the service user.
2022-10-31 21:10:14 The Plex service is installed. Let's get the user associated with the service.
2022-10-31 21:10:14 The Plex service user: WARNING\THISMESSAGEWILLSELFDESTRUCT.
2022-10-31 21:10:14 Plex local data folder: E:\.
2022-10-31 21:10:14 Updates folder: E:\Plex Media Server\Updates.
2022-10-31 21:10:14 Update channel: Plex Pass.
2022-10-31 21:10:14 Plex found in: C:\Program Files\Plex\Plex Media Server\Plex Media Server.exe.
2022-10-31 21:10:14 64-bit: True.
2022-10-31 21:10:14 Verify the updates folder is specified.
2022-10-31 21:10:14 Verify the updates folder, E:\Plex Media Server\Updates exists.
2022-10-31 21:10:14 Getting ready to download the latest package.
2022-10-31 21:10:14 Checking for the latest version from Plex.
2022-10-31 21:10:14 The update channel is set for Plex Pass.
2022-10-31 21:10:14 Sending request to Plex: https://plex.tv/api/downloads/5.json?channel=plexpass
2022-10-31 21:10:15 Parsing the information from Plex.
2022-10-31 21:10:15 The file, E:\Plex Media Server\Updates\1.29.2.6334-817e19b35\packages\PlexMediaServer-1.29.2.6334-817e19b35-x86_64.exe, exists. Checking to see if the package is valid.
2022-10-31 21:10:15 Checking if the installation package is valid.
2022-10-31 21:10:15 The package is valid. The checksums match.
2022-10-31 21:10:15 Since the package is valid - not downloading again.
2022-10-31 21:10:15 Latest packages file: E:\Plex Media Server\Updates\1.29.2.6334-817e19b35\packages\PlexMediaServer-1.29.2.6334-817e19b35-x86_64.exe
2022-10-31 21:10:15 The latest file version available for download is 1.29.2.6334.
2022-10-31 21:10:15 Current version: 1.29.1.6316.
2022-10-31 21:10:15 Latest version: 1.29.2.6334.
2022-10-31 21:10:17 The server is not in use continuing to perform the update.
2022-10-31 21:10:17 Displaying the update window.


Seems to be stuck on "Displaying the update window." Nothing seems to happen after that, although, the psupdate.exe executable is still running until I terminate it forcefully.

**Comment by TechieGuy12** [comment]
The "Display the update window." message is the last one before the actual window is displayed on the screen. From there you would click the **Updated** button to perform the update.

Was there a window displayed?

**Comment by Turbogame** [comment]
No. But I restarted my computer, and the GUI came up after running the executable. It then successfully upgraded the server. The beta release seems to have fixed my problem.

Thanks!
